### PR TITLE
Create vb

### PR DESCRIPTION
**Pull request by Landei**

### CODE REVIEW

**Comment by yukimono** [comment]
It's because you can't delete a program that is open, none of the programs work on windows.

**Comment by KarimGeiger** [comment]
hm.. is it possible to move it to the trash or something?

**Comment by yukimono** [comment]
Nop, Windows/NTFS locks the file if it's open or actively being read, can't write to, move or delete it.

**Comment by KarimGeiger** [comment]
Okay.. are there ways to run VB.NET code on Linux via Mono?

**Comment by nilsding** [comment]
Compiling VB.NET source works with `vbnc`.

However, I had to change some pieces in this file to let it compile.  I'll push them soon.

**Pull request closed without merging**
